import { Injectable, Logger } from '@nestjs/common';
import { DiscoveryService } from '@golevelup/nestjs-discovery';
import {
  EMITS_EVENT_METADATA_KEY,
  EmitsEventMetadata,
} from '../decorators/emits-event.decorator';
import {
  ON_EVENT_DOC_METADATA_KEY,
  OnEventDocMetadata,
} from '../decorators/on-event-doc.decorator';
import { writeFile, mkdir, readFile } from 'fs/promises';
import { join, parse } from 'path';
import { existsSync } from 'fs';

interface EmitterInfo {
  eventName: string;
  className: string;
  methodName: string;
  description: string;
}

interface ListenerInfo {
  eventName: string;
  className: string;
  methodName: string;
}

@Injectable()
export class EventDocumentationService {
  private readonly logger = new Logger(EventDocumentationService.name);

  constructor(private readonly discoveryService: DiscoveryService) {}

  async generate(): Promise<void> {
    this.logger.log('Starting event documentation generation...');

    const emitters = await this.discoverEmitters();
    const listeners = await this.discoverListeners();

    await this.generateCatalog(emitters, listeners);
    await this.generateFlowGraph(emitters, listeners);

    this.logger.log('✅ Event documentation generated successfully.');
  }

  private async discoverEmitters(): Promise<EmitterInfo[]> {
    const providers = await this.discoveryService.providersWithMetaAtKey<
      EmitsEventMetadata[]
    >(EMITS_EVENT_METADATA_KEY);
    const emitters: EmitterInfo[] = [];

    for (const provider of providers) {
      const metadataList = provider.meta;
      for (const metadata of metadataList) {
        if (metadata.onInit) {
          emitters.push({
            eventName: metadata.onInit.name,
            className: metadata.className,
            methodName: metadata.methodName,
            description:
              metadata.onInit.description || 'Fired when the operation starts.',
          });
        }
        if (metadata.onSuccess) {
          emitters.push({
            eventName: metadata.onSuccess.name,
            className: metadata.className,
            methodName: metadata.methodName,
            description:
              metadata.onSuccess.description ||
              'Fired on successful execution.',
          });
        }
        if (metadata.onFailure) {
          emitters.push({
            eventName: metadata.onFailure.name,
            className: metadata.className,
            methodName: metadata.methodName,
            description:
              metadata.onFailure.description || 'Fired on failed execution.',
          });
        }
      }
    }
    return emitters;
  }

  private async discoverListeners(): Promise<ListenerInfo[]> {
    const providers = await this.discoveryService.providersWithMetaAtKey<
      OnEventDocMetadata[]
    >(ON_EVENT_DOC_METADATA_KEY);
    const listeners: ListenerInfo[] = [];

    for (const provider of providers) {
      const metadataList = provider.meta;
      for (const metadata of metadataList) {
        listeners.push({
          eventName: metadata.eventName,
          className: metadata.className,
          methodName: metadata.methodName,
        });
      }
    }
    return listeners;
  }

  private async generateCatalog(
    emitters: EmitterInfo[],
    listeners: ListenerInfo[],
  ) {
    let content = '# Event Catalog\n\n';
    content +=
      'This document is auto-generated by the `EventDocumentationService`. Do not edit manually.\n\n';
    content += '| Event Name | Description | Emitted By | Listened By |\n';
    content += '|------------|-------------|------------|-------------|\n';

    const allEventNames = new Set([
      ...emitters.map((e) => e.eventName),
      ...listeners.map((l) => l.eventName),
    ]);

    for (const eventName of allEventNames) {
      const eventEmitters = emitters.filter((e) => e.eventName === eventName);
      const eventListeners = listeners.filter((l) => l.eventName === eventName);

      const description = eventEmitters[0]?.description || 'N/A';
      const emitterStr =
        eventEmitters
          .map((e) => `\`${e.className}.${e.methodName}\``)
          .join('<br/>') || 'N/A';
      const listenerStr =
        eventListeners
          .map((l) => `\`${l.className}.${l.methodName}\``)
          .join('<br/>') || 'N/A';

      content += `| \`${eventName}\` | ${description} | ${emitterStr} | ${listenerStr} |\n`;
    }

    const outputPath = join(
      process.cwd(),
      'docs',
      'generated',
      'EVENT_CATALOG.md',
    );
    await this.writeFileIfChanged(outputPath, content);
  }

  private async generateFlowGraph(
    emitters: EmitterInfo[],
    listeners: ListenerInfo[],
  ) {
    let content = '# Event Flow Graph\n\n';
    content +=
      'This document is auto-generated by the `EventDocumentationService`. Do not edit manually.\n\n';
    content += '```mermaid\n';
    content += 'graph TD;\n\n';

    const nodes = new Map<string, string>();
    let i = 0;
    const getNodeId = (name: string) => {
      if (!nodes.has(name)) {
        const cleanName = name.replace(/[^\w\s]/gi, '_');
        nodes.set(name, `N${i++}_${cleanName}`);
      }
      return nodes.get(name);
    };

    for (const emitter of emitters) {
      const emitterNode = `${emitter.className}.${emitter.methodName}`;
      content += `    ${getNodeId(emitterNode)}["${emitterNode}"]\n`;
    }
    for (const listener of listeners) {
      const listenerNode = `${listener.className}.${listener.methodName}`;
      content += `    ${getNodeId(listenerNode)}["${listenerNode}"]\n`;
    }
    const allEventNames = new Set([
      ...emitters.map((e) => e.eventName),
      ...listeners.map((l) => l.eventName),
    ]);
    for (const eventName of allEventNames) {
      content += `    ${getNodeId(eventName)}("${eventName}")\n`;
    }
    content += '\n';

    for (const emitter of emitters) {
      const emitterNode = `${emitter.className}.${emitter.methodName}`;
      content += `    ${getNodeId(emitterNode)} -- Emits --> ${getNodeId(
        emitter.eventName,
      )}\n`;
    }
    for (const listener of listeners) {
      const listenerNode = `${listener.className}.${listener.methodName}`;
      content += `    ${getNodeId(listener.eventName)} -- Triggers --> ${getNodeId(
        listenerNode,
      )}\n`;
    }

    content += '```\n';

    const outputPath = join(
      process.cwd(),
      'docs',
      'generated',
      'EVENT_FLOW.md',
    );
    await this.writeFileIfChanged(outputPath, content);
  }

  private async writeFileIfChanged(path: string, content: string) {
    const dir = parse(path).dir;
    if (!existsSync(dir)) {
      await mkdir(dir, { recursive: true });
    }

    if (existsSync(path)) {
      const existingContent = await readFile(path, 'utf-8');
      if (existingContent === content) {
        this.logger.log(`No changes for ${parse(path).base}. Skipping write.`);
        return;
      }
    }

    await writeFile(path, content);
    this.logger.log(`Documentation file ${parse(path).base} written.`);
  }
}
