// This file is auto-generated by the 'generate-event-types' command.
// Do not edit this file manually.

export const AppEvents = {
  /**
   *
   */
  USER_CREATION_INIT: {
    name: 'user.creation.init',
    type: 'onInit',
    description: '',
    payloadClass: undefined,
  },

  /**
   *
   */
  USER_CREATED_SUCCESS: {
    name: 'user.created.success',
    type: 'onSuccess',
    description: '',
    payloadClass: undefined,
  },

  /**
   *
   */
  USER_CREATED_FAILURE: {
    name: 'user.created.failure',
    type: 'onFailure',
    description: '',
    payloadClass: undefined,
  },

  /**
   *
   */
  USER_BUFFER_SUCCESS: {
    name: 'user.buffer.success',
    type: 'onSuccess',
    description: '',
    payloadClass: undefined,
  },

  /**
   *
   */
  USER_BUFFER_FAILURE: {
    name: 'user.buffer.failure',
    type: 'onFailure',
    description: '',
    payloadClass: undefined,
  },

  /**
   * Fired when a video is uploaded and ready for processing.
   */
  VIDEO_UPLOADED: {
    name: 'video.uploaded',
    type: 'onSuccess',
    description: 'Fired when a video is uploaded and ready for processing.',
    payloadClass: undefined,
  },

  /**
   * Fired if the initial video upload processing fails.
   */
  VIDEO_UPLOAD_FAILED: {
    name: 'video.upload.failed',
    type: 'onFailure',
    description: 'Fired if the initial video upload processing fails.',
    payloadClass: undefined,
  },

  /**
   * Fired when video transcoding is complete.
   */
  VIDEO_TRANSCODED_SUCCESS: {
    name: 'video.transcoded.success',
    type: 'onSuccess',
    description: 'Fired when video transcoding is complete.',
    payloadClass: undefined,
  },

  /**
   * Fired if video transcoding fails.
   */
  VIDEO_TRANSCODED_FAILURE: {
    name: 'video.transcoded.failure',
    type: 'onFailure',
    description: 'Fired if video transcoding fails.',
    payloadClass: undefined,
  },

  /**
   * Fired when a video thumbnail is generated.
   */
  THUMBNAIL_GENERATED_SUCCESS: {
    name: 'thumbnail.generated.success',
    type: 'onSuccess',
    description: 'Fired when a video thumbnail is generated.',
    payloadClass: undefined,
  },

  /**
   * Fired if thumbnail generation fails.
   */
  THUMBNAIL_GENERATED_FAILURE: {
    name: 'thumbnail.generated.failure',
    type: 'onFailure',
    description: 'Fired if thumbnail generation fails.',
    payloadClass: undefined,
  },

  /**
   * Fired when all video processing steps are confirmed to be complete.
   */
  VIDEO_READY_TO_PUBLISH: {
    name: 'video.ready.to.publish',
    type: 'onSuccess',
    description:
      'Fired when all video processing steps are confirmed to be complete.',
    payloadClass: undefined,
  },

  /**
   * Fired if the verification process fails.
   */
  VIDEO_VERIFICATION_FAILED: {
    name: 'video.verification.failed',
    type: 'onFailure',
    description: 'Fired if the verification process fails.',
    payloadClass: undefined,
  },

  /**
   * Fired when the video is fully processed and published.
   */
  VIDEO_PUBLISHED_SUCCESS: {
    name: 'video.published.success',
    type: 'onSuccess',
    description: 'Fired when the video is fully processed and published.',
    payloadClass: undefined,
  },

  /**
   * Fired if the final publishing step fails.
   */
  VIDEO_PUBLISHED_FAILURE: {
    name: 'video.published.failure',
    type: 'onFailure',
    description: 'Fired if the final publishing step fails.',
    payloadClass: undefined,
  },
} as const;
